Frappe update
thesis20/thesis_code pull request #27
Opened 2021-04-12 12:19 UTC by Eduardsen

2021-04-14 07:35 UTC, andpaacoke commented on model/Graph-conv-context-aware-idea-2021-wip/Data/Frappe/CFM-converter.py
> +all_offsets = [user_offset,weekday_offset,isweekend_offset,cost_offset,weather_offset,country_offset,city_offset, daytime_offset]
er man nødt til at hardcode alt det her

2021-04-14 07:36 UTC, andpaacoke commented on model/Graph-conv-context-aware-idea-2021-wip/Data/Frappe/CFM-converter.py
> +    n_cities = ratings['city'].nunique()
Den her bruger du vidst ikke

2021-04-14 07:37 UTC, andpaacoke commented on model/Graph-conv-context-aware-idea-2021-wip/Data/Frappe/frappe-load.py
> +    n_countries = ratings['country'].nunique()
n_countries bruger du heller ikke

2021-04-14 07:40 UTC, andpaacoke commented on model/Graph-conv-context-aware-idea-2021-wip/Data/Frappe/frappe-load.py
> +    print(f"DF after filter: {len_2}")
Er ikke sikker på hvad det her gør, måske en kommentar vville gøre godt xd

2021-04-14 07:43 UTC, andpaacoke commented on model/Graph-conv-context-aware-idea-2021-wip/Data/Frappe/frappefix.py
> +print(len(df['user'].unique()))
the double print pog

2021-04-14 07:46 UTC, andpaacoke requested changes
SÅ er der bare reviewed

2021-04-14 07:53 UTC, Eduardsen commented on model/Graph-conv-context-aware-idea-2021-wip/Data/Frappe/CFM-converter.py
> +all_offsets = [user_offset,weekday_offset,isweekend_offset,cost_offset,weather_offset,country_offset,city_offset, daytime_offset]
næh, egentligt ikke, det var barew hurtig blas xd

2021-04-14 07:53 UTC, Eduardsen commented on model/Graph-conv-context-aware-idea-2021-wip/Data/Frappe/CFM-converter.py
> +    n_cities = ratings['city'].nunique()
rtue

2021-04-14 07:54 UTC, Eduardsen commented on model/Graph-conv-context-aware-idea-2021-wip/Data/Frappe/frappefix.py
> +print(len(df['user'].unique()))
there it is

2021-04-14 11:56 UTC, Moesgaarda requested changes

2021-04-14 11:56 UTC, Moesgaarda commented on model/Graph-conv-context-aware-idea-2021-wip/model.py
> +        #pickle.dump(data, file_data)
nej

2021-04-14 12:04 UTC, andpaacoke approved these changes

2021-04-15 07:18 UTC, Moesgaarda approved these changes

2021-04-15 08:43 UTC, merged